# ruff: noqa: INP001  # planning/ is not a Python package; this is a standalone script
"""
Generate the planning index from frontmatter.

Run via ``just index``. Globs ``planning/changes/*/`` (each bundle's ``design.md``,
falling back to ``change.md``) and ``planning/decisions/*.md``, reads their
frontmatter, and prints a Markdown listing to stdout — changes grouped by lifecycle
status, then decisions newest-first. Never writes a file: the listing is a query over
the files, not a committed artifact.
"""

import pathlib
import sys


CHANGES_DIR = pathlib.Path(__file__).parent / "changes"
DECISIONS_DIR = pathlib.Path(__file__).parent / "decisions"
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("In progress", ("draft", "approved")),
    ("Shipped", ("shipped",)),
    ("Superseded", ("superseded",)),
)


def parse_frontmatter(text: str) -> dict[str, str]:
    """Parse a single-line-scalar YAML frontmatter block into a dict."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        key, sep, value = line.partition(": ")
        if not sep:
            continue
        cleaned = value.strip().strip('"').strip("'")
        fields[key.strip()] = "" if cleaned == "null" else cleaned
    return fields


def load_bundles() -> list[dict[str, str]]:
    """Read every bundle's spec frontmatter under ``CHANGES_DIR``."""
    bundles: list[dict[str, str]] = []
    for bundle in sorted(CHANGES_DIR.iterdir()):
        if not bundle.is_dir():
            continue
        spec = bundle / "design.md"
        if not spec.exists():
            spec = bundle / "change.md"
        if not spec.exists():
            continue
        fields = parse_frontmatter(spec.read_text(encoding="utf-8"))
        fields["path"] = f"changes/{bundle.name}/{spec.name}"
        fields["name"] = bundle.name
        bundles.append(fields)
    return bundles


def load_decisions() -> list[dict[str, str]]:
    """Read frontmatter from every decision file under ``DECISIONS_DIR``."""
    decisions: list[dict[str, str]] = []
    if not DECISIONS_DIR.is_dir():
        return decisions
    for path in sorted(DECISIONS_DIR.glob("*.md")):
        if path.name == "README.md" or path.name.startswith("_"):
            continue
        fields = parse_frontmatter(path.read_text(encoding="utf-8"))
        fields["path"] = f"decisions/{path.name}"
        fields["name"] = path.stem
        decisions.append(fields)
    return decisions


def format_row(bundle: dict[str, str]) -> str:
    """Render one bundle or decision as a Markdown list item."""
    slug = bundle.get("slug", "?")
    path = bundle.get("path", "")
    pr = bundle.get("pr") or "—"
    date = bundle.get("date", "")
    summary = bundle.get("summary") or "(no summary)"
    line = f"- **[{slug}]({path})** (#{pr}, {date}) — {summary}"
    if bundle.get("supersedes"):
        line += f" _(supersedes {bundle['supersedes']})_"
    if bundle.get("superseded_by"):
        line += f" _(superseded by {bundle['superseded_by']})_"
    return line


def render(bundles: list[dict[str, str]], decisions: list[dict[str, str]]) -> str:
    """Render the full Markdown listing: changes by status, then decisions."""
    out = ["# Planning index", "", "_Generated by `just index` — do not edit._", "", "## Changes", ""]
    for title, statuses in GROUPS:
        out += [f"### {title}", ""]
        rows = sorted(
            (b for b in bundles if b.get("status") in statuses),
            key=lambda b: b.get("name", ""),
            reverse=True,
        )
        out += [format_row(b) for b in rows] if rows else ["_None._"]
        out.append("")
    out += ["## Decisions", ""]
    decision_rows = sorted(decisions, key=lambda d: d.get("name", ""), reverse=True)
    out += [format_row(d) for d in decision_rows] if decision_rows else ["_None._"]
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    """Print the listing to stdout."""
    sys.stdout.write(render(load_bundles(), load_decisions()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
