# ruff: noqa: INP001  # planning/ is not a Python package; this is a standalone script
"""
Generate the planning change index from bundle frontmatter.

Run via ``just index``. Globs ``planning/changes/*/``, reads each bundle's
``design.md`` (falling back to ``change.md``) frontmatter, and prints a
Markdown listing grouped by lifecycle status to stdout. Never writes a file:
the listing is a query over the bundles, not a committed artifact.
"""

import pathlib
import sys


CHANGES_DIR = pathlib.Path(__file__).parent / "changes"
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("In progress", ("draft", "approved")),
    ("Shipped", ("shipped",)),
    ("Superseded", ("superseded",)),
)


def parse_frontmatter(text: str) -> dict[str, str]:
    """Parse a single-line-scalar YAML frontmatter block into a dict."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        key, sep, value = line.partition(": ")
        if not sep:
            continue
        cleaned = value.strip().strip('"').strip("'")
        fields[key.strip()] = "" if cleaned == "null" else cleaned
    return fields


def load_bundles() -> list[dict[str, str]]:
    """Read every bundle's spec frontmatter under ``CHANGES_DIR``."""
    bundles: list[dict[str, str]] = []
    for bundle in sorted(CHANGES_DIR.iterdir()):
        if not bundle.is_dir():
            continue
        spec = bundle / "design.md"
        if not spec.exists():
            spec = bundle / "change.md"
        if not spec.exists():
            continue
        fields = parse_frontmatter(spec.read_text(encoding="utf-8"))
        fields["path"] = f"changes/{bundle.name}/{spec.name}"
        fields["name"] = bundle.name
        bundles.append(fields)
    return bundles


def format_row(bundle: dict[str, str]) -> str:
    """Render one bundle as a Markdown list item."""
    slug = bundle.get("slug", "?")
    path = bundle.get("path", "")
    pr = bundle.get("pr") or "—"
    date = bundle.get("date", "")
    summary = bundle.get("summary") or "(no summary)"
    line = f"- **[{slug}]({path})** (#{pr}, {date}) — {summary}"
    if bundle.get("supersedes"):
        line += f" _(supersedes {bundle['supersedes']})_"
    if bundle.get("superseded_by"):
        line += f" _(superseded by {bundle['superseded_by']})_"
    return line


def render(bundles: list[dict[str, str]]) -> str:
    """Render the full grouped Markdown listing."""
    out = ["# Change index", "", "_Generated by `just index` — do not edit._", ""]
    for title, statuses in GROUPS:
        out += [f"## {title}", ""]
        rows = sorted(
            (b for b in bundles if b.get("status") in statuses),
            key=lambda b: b.get("name", ""),
            reverse=True,
        )
        out += [format_row(b) for b in rows] if rows else ["_None._"]
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    """Print the listing to stdout."""
    sys.stdout.write(render(load_bundles()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
