include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - riverpod_lint
  exclude:
    - "**/*.g.dart"
    - "lib/l10n/app_localizations*.dart"

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
